# Generated by Django 3.2.3 on 2021-07-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DWAapp', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('entryPeriod', models.CharField(max_length=6, verbose_name='Ingresso')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('note', models.IntegerField(verbose_name='Nota')),
                ('situation', models.CharField(max_length=10, verbose_name='Situação')),
            ],
        ),
    ]
